### ISSUE TITLE
A code error

### ISSUE THREAD

**Issue by lueluelu** [tonytan48/MSCL#2]
This is an attractive work, I want to run this experiment. I used the Amazon dataset to download via the link: https://www.cs.jhu.edu/~mdredze/datasets/sentiment/. (processed_stars.tar.gz(33 M)(https://www.cs.jhu.edu/~mdredze/datasets/sentiment/processed_stars.tar.gz)).
The following error is displayed after placing the dataset in the specified location.May I ask how to improve this problem? Thank you!

> Traceback (most recent call last):
  File "MSCL-main/sentiment_analysis/mscl_domain.py", line 843, in <module>
    train_data[domain] = xlm_r_train(train_data[domain],tokenizer,max_length, domain_label_map)
  File "MSCL-main/sentiment_analysis/mscl_domain.py", line 146, in xlm_r_train
    encoded = torch.LongTensor(tokenizer.encode(pair[2],max_length=max_length, truncation = True, pad_to_max_length=True)).to(device)
IndexError: list index out of range

**Comment by lueluelu** [comment]
If it's a data set error, could you send me a copy of the document you have handled for my reference? My email is 1056566733@qq.com. Thank you!

**Comment by Chunngai** [comment]
Hello. What's your solution?
